In [3]:
import numpy as np
import networkx as nx
import pandas as pd
import hypernetx as hnx
import time
import random

from helpers import *

In [3]:
year = 2015

data = pd.read_csv(f"data/rete_{year}.csv")

valid_edges = (
    data.groupby("CF Partecipata")["CF Comune"]
    .nunique()
    .loc[lambda s: s > 1]
    .index
)
filtered_data = data[data["CF Partecipata"].isin(valid_edges)].copy()

H = hnx.Hypergraph(
    filtered_data,
    edge_col="CF Partecipata",
    node_col="CF Comune",
    cell_weight_col="Quota"
 )

print(f"Original edges: {data['CF Partecipata'].nunique()}")
print(f"Filtered edges: {filtered_data['CF Partecipata'].nunique()}")
print(f"Number of nodes: {len(H.nodes)}")
print(f"Number of edges: {len(H.edges)}")

Original edges: 12558
Filtered edges: 8756
Number of nodes: 7858
Number of edges: 8756

In [ ]:
M = np.array(H.incidence_matrix(weights="weight").todense())
print(I.shape)

(7858, 8756)

In [128]:
A = M @ M.T
A = A - np.diag(A.diagonal())
print(A.shape)

(7858, 7858)

In [129]:
(A.sum(axis=1) == 0).sum()

np.int64(0)

In [130]:
for i,components in enumerate(H.s_components(s=1)):
  print(f"Component {i}: {components}")

Component 0: {np.int64(2169470982), np.int64(2832990218), np.int64(2388000792), np.int64(8715730969), np.int64(2309980189), np.int64(91048640550), np.int64(3179610153), np.int64(6609961005), np.int64(3895590960), np.int64(3214180402), np.int64(3709960243), np.int64(6523420724), np.int64(1388970038), np.int64(4201250877), np.int64(10927571009), np.int64(93049520195), np.int64(2736160835), np.int64(12357501001), np.int64(12255101003), np.int64(2066710605), np.int64(2446000206), np.int64(8566440015), np.int64(91002470481), np.int64(2003370067), np.int64(90035880021), np.int64(1992360022), np.int64(2081030229), np.int64(7108460630), np.int64(9783640155), np.int64(2980610139), np.int64(3071410272), np.int64(4246470753), np.int64(2184020069), np.int64(92005040230), np.int64(3273850986), np.int64(1771110507), np.int64(5940510828), np.int64(2198700151), np.int64(11670651006), np.int64(1970110597), np.int64(554500231), np.int64(96041730183), np.int64(2913370249), np.int64(2600960138), np.int64(1111130256), np.int64(8604450968), np.int64(2730360985), np.int64(12564431000), np.int64(90008060056), np.int64(6655180963), np.int64(2115960995), np.int64(90022510755), np.int64(3208020135), np.int64(1897431209), np.int64(2734620848), np.int64(80003530930), np.int64(3211690163), np.int64(3451650232), np.int64(858030273), np.int64(3267330243), np.int64(3139240133), np.int64(6558220486), np.int64(1197310152), np.int64(3550380236), np.int64(3535700177), np.int64(5128650966), np.int64(97662370010), np.int64(1553760479), np.int64(8156020961), np.int64(3500671205), np.int64(7525990631), np.int64(2148860139), np.int64(1966440693), np.int64(1294500085), np.int64(2173960440), np.int64(2096070905), np.int64(12931531003), np.int64(1565360383), np.int64(9316040964), np.int64(2228060428), np.int64(4693590285), np.int64(3195830546), np.int64(851280156), np.int64(9645130015), np.int64(6892060960), np.int64(80003170596), np.int64(1600880932), np.int64(2296480037), np.int64(2314240306), np.int64(94001430837), np.int64(238190904), np.int64(6240371002), np.int64(1808400699), np.int64(2796290365), np.int64(3643900230), np.int64(9933390156), np.int64(7762510159), np.int64(3256910161), np.int64(3605070162), np.int64(2077720924), np.int64(1925120352), np.int64(2223440237), np.int64(2277540205), np.int64(1725890931), np.int64(1749680508), np.int64(1720910205), np.int64(2245460361), np.int64(2966290831), np.int64(1705050514), np.int64(2448490900), np.int64(2702541208), np.int64(3757080985), np.int64(6359220636), np.int64(2750480796), np.int64(3654910367), np.int64(1942880673), np.int64(2985591201), np.int64(1762460069), np.int64(4597940651), np.int64(2307490223), np.int64(2320040369), np.int64(91010040243), np.int64(3988160960), np.int64(1362330050), np.int64(4029120963), np.int64(9545581002), np.int64(1848050124), np.int64(1419280852), np.int64(3072360922), np.int64(2208170460), np.int64(567640552), np.int64(3319071209), np.int64(2173600236), np.int64(4601250287), np.int64(3088220656), np.int64(114590193), np.int64(738460146), np.int64(3059220982), np.int64(6078890487), np.int64(3348300280), np.int64(93035790844), np.int64(8558150150), np.int64(2026570248), np.int64(1918730761), np.int64(8188690963), np.int64(772080149), np.int64(3122430485), np.int64(3943760409), np.int64(1241350683), np.int64(2097480228), np.int64(4498620964), np.int64(2045510183), np.int64(1565590062), np.int64(2379121201), np.int64(90035880500), np.int64(1674510902), np.int64(1823900228), np.int64(124060229), np.int64(1599570502), np.int64(3737190987), np.int64(2427880022), np.int64(2438660694), np.int64(3289580122), np.int64(10864231005), np.int64(91024720483), np.int64(5827920488), np.int64(96000410223), np.int64(1404240499), np.int64(224330365), np.int64(2371650181), np.int64(5405541003), np.int64(7586710159), np.int64(1429570193), np.int64(6246990482), np.int64(3666510486), np.int64(845120153), np.int64(1463190171), np.int64(12904170151), np.int64(9739961002), np.int64(2431550124), np.int64(12627641009), np.int64(91006010036), np.int64(2367390396), np.int64(549520062), np.int64(6755680961), np.int64(2602140358), np.int64(3642720969), np.int64(4405920481), np.int64(1392050918), np.int64(6269600489), np.int64(1763050224), np.int64(2721710834), np.int64(9107211006), np.int64(3621290752), np.int64(1040450312), np.int64(2604860169), np.int64(2484470543), np.int64(4495541007), np.int64(6266290961), np.int64(92007760660), np.int64(1007780628), np.int64(978420503), np.int64(1723630362), np.int64(2011890460), np.int64(4348511009), np.int64(4216980260), np.int64(3094610726), np.int64(1605370665), np.int64(80001270570), np.int64(8461321005), np.int64(3506340656), np.int64(3042280242), np.int64(5869830967), np.int64(2716140344), np.int64(304120637), np.int64(7321060159), np.int64(3568010049), np.int64(2459370306), np.int64(1760920387), np.int64(3982000964), np.int64(1487700807), np.int64(9017230153), np.int64(3774350163), np.int64(2586280790), np.int64(515900249), np.int64(5132551002), np.int64(3357410137), np.int64(1776550749), np.int64(4712760158), np.int64(1035830114), np.int64(932840291), np.int64(3299640163), np.int64(2963080045), np.int64(3270280047), np.int64(2143290225), np.int64(6223790962), np.int64(1092780913), np.int64(7104430967), np.int64(2582020984), np.int64(1587020668), np.int64(70550397), np.int64(6065030014), np.int64(872940416), np.int64(2373550983), np.int64(2899870600), np.int64(7155680155), np.int64(3554870174), np.int64(2609120163), np.int64(4451500963), np.int64(6991020964), np.int64(2550760355), np.int64(2064090026), np.int64(3267560369), np.int64(2636940211), np.int64(2974450617), np.int64(3229451202), np.int64(1925940163), np.int64(3781100486), np.int64(12868781001), np.int64(2654340047), np.int64(1855030225), np.int64(3145270231), np.int64(2260370396), np.int64(2193130461), np.int64(2249360351), np.int64(7426900960), np.int64(1606550497), np.int64(92035220448), np.int64(2581660640), np.int64(2761130984), np.int64(1500840937), np.int64(3821110248), np.int64(614040558), np.int64(5723390968), np.int64(3845260284), np.int64(3508700170), np.int64(1200620555), np.int64(9925461007), np.int64(2487190544), np.int64(5941330960), np.int64(5103780879), np.int64(4766270484), np.int64(2087060501), np.int64(5222990870), np.int64(4876370968), np.int64(3426190363), np.int64(10595370015), np.int64(93040870433), np.int64(1366590501), np.int64(2796160048), np.int64(2385970229), np.int64(1362920504), np.int64(1379730490), np.int64(4821681212), np.int64(1631290432), np.int64(166790212), np.int64(1422820421), np.int64(462390345), np.int64(1034290252), np.int64(1100710993), np.int64(6684410969), np.int64(2219770977), np.int64(1188660326), np.int64(12924290153), np.int64(6100911210), np.int64(1931150443), np.int64(1920730221), np.int64(1311540338), np.int64(1700070517), np.int64(2472281209), np.int64(1281590396), np.int64(2499380349), np.int64(279250047), np.int64(2106590348), np.int64(3417900176), np.int64(2096301201), np.int64(3351970961), np.int64(1435010192), np.int64(8308130965), np.int64(4261020822), np.int64(11889280159), np.int64(3984000160), np.int64(4249420961), np.int64(90045580447), np.int64(2707850406), np.int64(2115110062), np.int64(2360870063), np.int64(1426850994), np.int64(3652650163), np.int64(2546140340), np.int64(2206500023), np.int64(92007630012), np.int64(7170720960), np.int64(2213840065), np.int64(2678490307), np.int64(1431930054), np.int64(4469720264), np.int64(2521990347), np.int64(9571960013), np.int64(4934730963), np.int64(3870590167), np.int64(2641200346), np.int64(7447381216), np.int64(2104100066), np.int64(6999540963), np.int64(3216770275), np.int64(4032300271), np.int64(2119730428), np.int64(2581890304), np.int64(4847830280), np.int64(8003061002), np.int64(1896350988), np.int64(9557280014), np.int64(816350482), np.int64(3124790548), np.int64(273450262), np.int64(3384870170), np.int64(4418110757), np.int64(8710260012), np.int64(2046690604), np.int64(3180660015), np.int64(7820870967), np.int64(1087440192), np.int64(2373190988), np.int64(86001190221), np.int64(3964110161), np.int64(13022791001), np.int64(1542260060), np.int64(11476600157), np.int64(2662991203), np.int64(10223650150), np.int64(511870313), np.int64(1681950067), np.int64(2029880693), np.int64(1122010505), np.int64(10062661003), np.int64(1486980491), np.int64(1660650894), np.int64(6986040720), np.int64(3204941201), np.int64(7877920152), np.int64(2279540120), np.int64(10384410014), np.int64(2696250782), np.int64(2106000801), np.int64(9606170018), np.int64(3078260134), np.int64(2171930023), np.int64(11867850155), np.int64(2389050796), np.int64(2105050542), np.int64(5026710961), np.int64(4379870654), np.int64(882050495), np.int64(10932291007), np.int64(96020760011), np.int64(1615660493), np.int64(2647590351), np.int64(5633770960), np.int64(10519021009), np.int64(7292650962), np.int64(1055720914), np.int64(2751170016), np.int64(5732500961), np.int64(1913390561), np.int64(1349420529), np.int64(4694050289), np.int64(551880180), np.int64(1364690428), np.int64(1793820158), np.int64(6401000960), np.int64(8735720966), np.int64(1707050504), np.int64(6579160588), np.int64(10502080012), np.int64(8589510158), np.int64(1763870225), np.int64(197690902), np.int64(4258760232), np.int64(10558441001), np.int64(1209140779), np.int64(8876820013), np.int64(3055650364), np.int64(451610174), np.int64(3339290177), np.int64(2019100227), np.int64(8769341002), np.int64(2912650831), np.int64(1745520211), np.int64(6894650966), np.int64(5440570967), np.int64(627050073), np.int64(2263320166), np.int64(2345240168), np.int64(84003030636), np.int64(1856570989), np.int64(92051670641), np.int64(1306560119), np.int64(2514880125), np.int64(3436480127), np.int64(2242840201), np.int64(5750851213), np.int64(5274830487), np.int64(10532751004), np.int64(2132870813), np.int64(12201920159), np.int64(5947000484), np.int64(1053820583), np.int64(9251980968), np.int64(1946420906), np.int64(1361020595), np.int64(1830160063), np.int64(3242690240), np.int64(1086260930), np.int64(6234080965), np.int64(6828000965), np.int64(2439710407), np.int64(1825900234), np.int64(3215460043), np.int64(3511060174), np.int64(2245920463), np.int64(3424650962), np.int64(2346550995), np.int64(3501000404), np.int64(2312341205), np.int64(11163240150), np.int64(2115110617), np.int64(1737590495), np.int64(3445950177), np.int64(1034290914), np.int64(180160228), np.int64(2561640166), np.int64(6206260967), np.int64(2365490925), np.int64(1225590510), np.int64(1997080302), np.int64(3628140273), np.int64(3226470130), np.int64(2381940465), np.int64(2980841205), np.int64(953190147), np.int64(80030140166), np.int64(10607200010), np.int64(2258110218), np.int64(1565460241), np.int64(1475970834), np.int64(1198360339), np.int64(2244380446), np.int64(3953690405), np.int64(3754460966), np.int64(1876100908), np.int64(2317190961), np.int64(7437190965), np.int64(1883080507), np.int64(8376420157), np.int64(1907590978), np.int64(8969520967), np.int64(8682800969), np.int64(1970800460), np.int64(3451160406), np.int64(6002640727), np.int64(92020770647), np.int64(2304280411), np.int64(1421510494), np.int64(1965360991), np.int64(2074150752), np.int64(995100526), np.int64(1389070192), np.int64(1523550067), np.int64(2768570232), np.int64(1086850938), np.int64(8269531003), np.int64(1533970305), np.int64(1470990209), np.int64(2024540037), np.int64(1492780935), np.int64(83004000135), np.int64(13068470155), np.int64(711690131), np.int64(3361310612), np.int64(12501551001), np.int64(13279791001), np.int64(1701480350), np.int64(1370130336), np.int64(2345240481), np.int64(7197231009), np.int64(1725400996), np.int64(2262370220), np.int64(185370541), np.int64(3500640176), np.int64(596150201), np.int64(2210400186), np.int64(167610302), np.int64(3137800128), np.int64(3984820161), np.int64(4237330370), np.int64(2337540047), np.int64(4123690960), np.int64(3129640920), np.int64(371820507), np.int64(3103590364), np.int64(1198000091), np.int64(4518840287), np.int64(3035400161), np.int64(2030110692), np.int64(2243430374), np.int64(3204450278), np.int64(3171551207), np.int64(12769921003), np.int64(1954580468), np.int64(1266190329), np.int64(4379740154), np.int64(1982040063), np.int64(2249820164), np.int64(92008450055), np.int64(1122240524), np.int64(13264390157), np.int64(2147420174), np.int64(3828910103), np.int64(11468671000), np.int64(9889450012), np.int64(91025410084), np.int64(1227950118), np.int64(2012350506), np.int64(1500350507), np.int64(1782450223), np.int64(3337390128), np.int64(4565960756), np.int64(3841460284), np.int64(671320125), np.int64(80010250308), np.int64(2696710215), np.int64(962660429), np.int64(4950820961), np.int64(4602660963), np.int64(7510820967), np.int64(6589220968), np.int64(2396850279), np.int64(2511210607), np.int64(1409910898), np.int64(2551220342), np.int64(2581170301), np.int64(3060140161), np.int64(1287260291), np.int64(1846020228), np.int64(2305230985), np.int64(2903410831), np.int64(2159020177), np.int64(1957070996), np.int64(1531480216), np.int64(3308030109), np.int64(3767470242), np.int64(91001260198), np.int64(1970210983), np.int64(9428601000), np.int64(4035020967), np.int64(3482880170), np.int64(3246590123), np.int64(5965220014), np.int64(9725610159), np.int64(7451510965), np.int64(9107540156), np.int64(13582371004), np.int64(2722990278), np.int64(2056030410), np.int64(3466660044), np.int64(4402350286), np.int64(2276821200), np.int64(9378040019), np.int64(493750491), np.int64(1368230114), np.int64(927500520), np.int64(2535590125), np.int64(12250450157), np.int64(702220526), np.int64(80002910448), np.int64(930810098), np.int64(3355740402), np.int64(2425620735), np.int64(9244150018), np.int64(2071890186), np.int64(811010321), np.int64(2055670034), np.int64(9547680018), np.int64(4480370966), np.int64(2287110429), np.int64(1522960671), np.int64(602540320), np.int64(4476700960), np.int64(1087310114), np.int64(1227950373), np.int64(7569180966), np.int64(2293860645), np.int64(4845340969), np.int64(7597001002), np.int64(2903410989), np.int64(2026080560), np.int64(1250330931), np.int64(1815710015), np.int64(9989491007), np.int64(7336560961), np.int64(9331870015), np.int64(862980422), np.int64(4884990286), np.int64(93014100304), np.int64(3053390161), np.int64(3066661202), np.int64(200870228), np.int64(2984610135), np.int64(123570525), np.int64(1972210023), np.int64(8258161002), np.int64(12733090158), np.int64(1905690994), np.int64(7903840630), np.int64(4601710967), np.int64(2540800378), np.int64(1378060667), np.int64(6400280969), np.int64(4498000266), np.int64(8424950155), np.int64(3481930125), np.int64(91146750350), np.int64(10565061008), np.int64(4451010963), np.int64(6854511000), np.int64(3155200409), np.int64(3375860123), np.int64(7937690019), np.int64(2398620068), np.int64(826050981), np.int64(4429220264), np.int64(95174560169), np.int64(10145860010), np.int64(2574780843), np.int64(795380146), np.int64(3461450177), np.int64(6398380482), np.int64(1697450433), np.int64(492440011), np.int64(4284680651), np.int64(2002880975), np.int64(3916040656), np.int64(3118270929), np.int64(2400160210), np.int64(5132650960), np.int64(1954220503), np.int64(4339960280), np.int64(5096770010), np.int64(2480540125), np.int64(8293911007), np.int64(1261210080), np.int64(1459980767), np.int64(9959410151), np.int64(6703090156), np.int64(123210221), np.int64(1761610227), np.int64(1504610807), np.int64(1525090807), np.int64(6830230014), np.int64(2573830656), np.int64(5224040963), np.int64(6473320965), np.int64(1618610701), np.int64(5527570963), np.int64(1492290067), np.int64(6743231000), np.int64(1897400857), np.int64(1489570331), np.int64(2303330845), np.int64(1248070193), np.int64(2776730166), np.int64(907610679), np.int64(138250808), np.int64(10965060154), np.int64(1952090684), np.int64(4723870269), np.int64(2125990461), np.int64(95108270653), np.int64(1701710400), np.int64(3297970752), np.int64(1484950082), np.int64(6977030722), np.int64(91004340807), np.int64(1078430293), np.int64(91012270681), np.int64(976030304), np.int64(4701031009), np.int64(1629260389), np.int64(82000710259), np.int64(5594811001), np.int64(387320443), np.int64(4065561211), np.int64(4226550400), np.int64(5632101001), np.int64(2159250063), np.int64(3136621202), np.int64(2875460244), np.int64(1545210518), np.int64(3544550043), np.int64(2106460831), np.int64(1844120236), np.int64(80001010349), np.int64(2169080500), np.int64(1535380156), np.int64(1894910668), np.int64(1591970510), np.int64(1812630224), np.int64(2103610065), np.int64(13283560152), np.int64(4670360280), np.int64(35130079), np.int64(11942071009), np.int64(1629850338), np.int64(83002690275), np.int64(3552021218), np.int64(13157010151), np.int64(9747041003), np.int64(2350090987), np.int64(4543810289), np.int64(3797650169), np.int64(1881180929), np.int64(3835300611), np.int64(1282280195), np.int64(2208500484), np.int64(1734970120), np.int64(2588740361), np.int64(12883430154), np.int64(226790160), np.int64(90005900049), np.int64(4129950483), np.int64(1030130452), np.int64(92008680214), np.int64(3259370264), np.int64(80061860633), np.int64(1966770974), np.int64(2130840354), np.int64(2919140133), np.int64(3554020135), np.int64(4136340264), np.int64(1300990767), np.int64(71600944), np.int64(10162441009), np.int64(2522090303), np.int64(2544110402), np.int64(124390212), np.int64(1456900933), np.int64(92024900422), np.int64(3518860105), np.int64(1925090126), np.int64(2327710543), np.int64(579210063), np.int64(490900305), np.int64(97341770580), np.int64(7611911004), np.int64(10499591005), np.int64(1052740451), np.int64(903580520), np.int64(3580300139), np.int64(1732250475), np.int64(10977250157), np.int64(9850850158), np.int64(2143980395), np.int64(6081710961), np.int64(3290041205), np.int64(4181920630), np.int64(10922331003), np.int64(2345700229), np.int64(791350150), np.int64(1855130504), np.int64(1850510221), np.int64(3944450968), np.int64(2329250712), np.int64(5494770588), np.int64(1157860253), np.int64(3279031201), np.int64(5886380962), np.int64(2121730978), np.int64(2385120163), np.int64(1233030061), np.int64(1617890221), np.int64(3532000175), np.int64(80012250041), np.int64(8869120967), np.int64(4226190280), np.int64(2606140362), np.int64(197430218), np.int64(2293140428), np.int64(3360820173), np.int64(6285790157), np.int64(137530317), np.int64(1421380559), np.int64(6500781007), np.int64(6220811217), np.int64(105450456), np.int64(2804190169), np.int64(7930711002), np.int64(1329040354), np.int64(4814670826), np.int64(562400242), np.int64(3262090230), np.int64(821300225), np.int64(618630149), np.int64(2289110021), np.int64(93069970437), np.int64(7344000018), np.int64(1746340890), np.int64(1201540133), np.int64(10421210153), np.int64(2240810032), np.int64(3422260277), np.int64(1528040502), np.int64(1086950456), np.int64(5779360824), np.int64(4377250875), np.int64(9953021004), np.int64(2392230989), np.int64(8847101006), np.int64(7627770964), np.int64(1664060504), np.int64(2898070616), np.int64(91010010204), np.int64(2145160285), np.int64(1285590111), np.int64(2865400929), np.int64(8317570151), np.int64(760450155), np.int64(4133850232), np.int64(6417190011), np.int64(92000390267), np.int64(3166211205), np.int64(3615460486), np.int64(2362510469), np.int64(3406400659), np.int64(3995471004), np.int64(2508000417), np.int64(4437380266), np.int64(292490414), np.int64(5181410480), np.int64(12958371002), np.int64(87007530170), np.int64(2193460413), np.int64(6998691007), np.int64(1497140416), np.int64(97001770177), np.int64(3951070402), np.int64(1123290312), np.int64(1254100173), np.int64(8458570960), np.int64(3644460242), np.int64(5337910482), np.int64(1926270164), np.int64(9134410969), np.int64(1958350041), np.int64(1285590236), np.int64(4192341214), np.int64(1269730527), np.int64(8311540960), np.int64(1876790500), np.int64(8884980965), np.int64(2964950246), np.int64(92001570032), np.int64(3558870261), np.int64(2561740024), np.int64(2823130360), np.int64(2394230011), np.int64(3757640960), np

In [124]:
data[data["CF Partecipata"] == 80003090638]

          CF Comune            Comune  CF Partecipata  Quota
197383  80014890638  COMUNE DI NAPOLI     80003090638  100.0

In [105]:
data[data["CF Comune"] == 80014890638]

          CF Comune            Comune  CF Partecipata       Quota
197365  80014890638  COMUNE DI NAPOLI       284210630   66.306366
197366  80014890638  COMUNE DI NAPOLI     95000950634  100.000000
197367  80014890638  COMUNE DI NAPOLI      5888670634   70.330160
197368  80014890638  COMUNE DI NAPOLI      4378020632    9.855670
197369  80014890638  COMUNE DI NAPOLI      7240690631   18.520000
197370  80014890638  COMUNE DI NAPOLI      7295621218    0.295670
197371  80014890638  COMUNE DI NAPOLI      7074950630    3.315318
197372  80014890638  COMUNE DI NAPOLI      5585671216    5.273277
197373  80014890638  COMUNE DI NAPOLI      6621571212    0.142668
197374  80014890638  COMUNE DI NAPOLI      7942440632  100.000000
197375  80014890638  COMUNE DI NAPOLI      5152190657    0.029978
197376  80014890638  COMUNE DI NAPOLI      6737011210  100.000000
197377  80014890638  COMUNE DI NAPOLI      4721631218   91.768120
197378  80014890638  COMUNE DI NAPOLI      7494740637  100.000000
197379  80014890638  COMUNE DI NAPOLI      7487100633  100.000000
197380  80014890638  COMUNE DI NAPOLI      7833540631   53.461600
197381  80014890638  COMUNE DI NAPOLI      7447381216    0.526690
197382  80014890638  COMUNE DI NAPOLI      3166090633   12.500000
197383  80014890638  COMUNE DI NAPOLI     80003090638  100.000000
197384  80014890638  COMUNE DI NAPOLI      5479261215    0.004391
197385  80014890638  COMUNE DI NAPOLI      4777011216  100.000000
197386  80014890638  COMUNE DI NAPOLI      7233980635    9.803922
197387  80014890638  COMUNE DI NAPOLI      6122071217    2.853365
197388  80014890638  COMUNE DI NAPOLI      7577090637  100.000000
197389  80014890638  COMUNE DI NAPOLI      7679350632  100.000000
197390  80014890638  COMUNE DI NAPOLI      5452210635   73.332240
197391  80014890638  COMUNE DI NAPOLI      5785311217   13.261273
197392  80014890638  COMUNE DI NAPOLI      7899100635   91.768120
197393  80014890638  COMUNE DI NAPOLI      7012251216   25.000000

# Exp

In [4]:
year = 2015

data = pd.read_csv(f"data/rete_{year}.csv")

valid_edges = (
    data.groupby("CF Partecipata")["CF Comune"]
    .nunique()
    .loc[lambda s: s > 1]
    .index
)
filtered_data = data[data["CF Partecipata"].isin(valid_edges)].copy()

H = hnx.Hypergraph(
    filtered_data,
    edge_col="CF Partecipata",
    node_col="CF Comune",
    cell_weight_col="Quota"
 )

print(f"Original edges: {data['CF Partecipata'].nunique()}")
print(f"Filtered edges: {filtered_data['CF Partecipata'].nunique()}")
print(f"Number of nodes: {len(H.nodes)}")
print(f"Number of edges: {len(H.edges)}")


I = np.array(H.incidence_matrix(weights="weight").todense())
print(I.shape)

Original edges: 12558
Filtered edges: 8756
Number of nodes: 7858
Number of edges: 8756
(7858, 8756)

In [5]:
w = np.ones(I.shape[1]) * 0.1
x0 = np.zeros(len(H.nodes))
k = 10

idx = np.random.choice(np.arange(len(H.nodes)), size = k)
x0[idx] = 1

h0 = 1.0
l0 = 1.0
theta_l = 2.0
theta_h = 10.0
gamma = 0.0
eps = 0.1
params = (h0, l0, theta_l, theta_h, gamma, eps)

spread ,spread_hist, x, actives = influence_spread(I, w, x0, params)

In [6]:
actives

[np.int64(10),
 np.int64(182),
 np.int64(1307),
 np.int64(4820),
 np.int64(7070),
 np.int64(7448),
 np.int64(7587)]

In [21]:
for elem in x:
    print(elem.sum())

10.0
68.06586530334613
214.54123404183633
209.52142755769216
57.27841518653884
12.037462765040946
2.4305268255616386